### ISSUE TITLE
lifecycle component?

### ISSUE THREAD

**Issue by juanpablocs** [jackyef/react-isomorphic-data#11]
Any example with the life cycle of a traditional component?

```js
class Component extends React.Component {

  state = { data: [] };

  async componentDidMount(){
    const data = await useData(API);
    this.setState({ data });
  }

  render(){
     console.log('data', data)
  }
}
```
I have not tried

**Comment by jackyef** [comment]
Hi @juanpablocs! Since hooks can only be used inside a function component, for class component you can use the HOC `withData()` or `withLazyData()` instead.

An example of how to use it can be seen in the docs: https://react-isomorphic-data.netlify.com/docs/hocs/withdata

**Comment by juanpablocs** [comment]
Your project is interesting, congratulations. Could you support `axios` please?

**Comment by juanpablocs** [comment]
I'm testing on my project and it doesn't work :cry: 

```js
import React from 'react';
import { withData } from 'react-isomorphic-data';

class Category extends React.Component {
    render() {
        console.log(this.props.categories);
        return <p>Category</p>;
    }
}

const CategoryHoc = withData({
    url: `${API_BASE}/categories`,
    name: 'categories'
})(Category);

export { CategoryHoc as Category };
```

![Screenshot from 2019-11-02 10-13-53](https://user-images.githubusercontent.com/9310466/68072970-86faa280-fd59-11e9-8350-8562a485b1ab.png)

**Comment by jackyef** [comment]
> Your project is interesting, congratulations. Could you support axios please?

Unfortunately, in the interest of keeping the library small, I prefer to keep the library to use the native `fetch` API for now.

> I'm testing on my project and it doesn't work 😢

Interesting, may I look at your repo to find out what the problem may be? Or can you provide me with a reproduction?

**Comment by jackyef** [comment]
Closing due to the inactivity. Feel free to bump this issue if you still have questions!
