### ISSUE TITLE
Have something like `ssrForceFetchDelay`

### ISSUE THREAD

**Issue by jackyef** [jackyef/react-isomorphic-data#14]
This would prevent a data that is already in the cache to be fetched immediately again upon client side hydration.

Reference: https://www.apollographql.com/docs/react/performance/server-side-rendering/

**Comment by umakantp** [comment]
Is there any plan to fix this?

**Comment by jackyef** [comment]
Hi @umakantp, sure!

I wasn't convinced that `ssrForceFetchDelay` is the best way to go, but I guess I haven't really found another way yet.

**Comment by umakantozy** [comment]
Thanks for the reply jack. Are you having any plans anytime soon for this?

**Comment by umakantp** [comment]
Thanks for the reply jack. Are you having any plans anytime soon for this?
