### ISSUE TITLE
Implement subscription model for better performance

### ISSUE THREAD

**Issue by jackyef** [jackyef/react-isomorphic-data#35]
Context + hooks will cause many re-renders.

Consider using subscription model like redux did to improve on this situation.

https://github.com/facebook/react/issues/15156

We can learn from redux journey https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/
https://github.com/reduxjs/react-redux/blob/master/src/hooks/useSelector.js

Sebastian from facebook team also says that the new Context API is not meant to be used to propagate state: https://twitter.com/sebmarkbage/status/1219836431972978689

I am now thinking of either add a tip in the docs to let users memoize their expensive tree themselves, instead of doing this from the library itself, since React does not seem to provide a good way to do this at the moment.

**Comment by dai-shi** [comment]
Hi, just found this issue from the react issue.
Consider using `use-subscription` from the React team.
I would also suggest to have a look at [my library](https://react-tracked.js.org), and if you like it, consider it too. 😄

**Comment by jackyef** [comment]
@dai-shi Hey, nice library you have there! Would definitely check it out to see if it fits my needs here. Thanks for providing some references!
