### ISSUE TITLE
fetchPolicy option as global during defining createDataClient

### ISSUE THREAD

**Issue by umakantp** [jackyef/react-isomorphic-data#55]
This would really help if we can define fetch policy globally instead if defining during each use of useData.

Most API's will follow common cached + network policy while there could be only exception 1/2 API's will be network only

**Comment by jackyef** [comment]
Currently, the default `fetchPolicy` is `cache-first`, which avoid having extra network calls. I guess having the ability to set a default `fetchPolicy` is okay. Let me see if I can come up with something.
